[package]
name = "gram-schmidt"
version = "0.2.0"
authors = ["Richard Janis Goldschmidt <janis.beckert@gmail.com>"]

[dependencies]
blas = "0.15"
ndarray = "0.9"
ndarray-parallel = "0.3"

[dev-dependencies]
ndarray-rand = "0.5"
rand = "0.3"
