[package]
name = "gram-schmidt"
version = "0.3.0"
authors = ["Richard Janis Goldschmidt <janis.beckert@gmail.com>"]

[dependencies]
ndarray = "0.10"

[dependencies.blas]
version = "0.16"
default-features = false

[dependencies.ndarray-parallel]
version = "0.5"
optional = true

[dev-dependencies]
ndarray-rand = "0.6"
rand = "0.3"

[features]
parallel = ["ndarray-parallel"]

# A feature used for testing and benching.
blas-openblas = ["blas/openblas"]
test = ["blas-openblas", "parallel"]
